/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "APIEndpoint": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "IdentityPool": {
      "id": string
      "type": "sst.aws.CognitoIdentityPool"
    }
    "JMDatabase": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "JobTrendrUserPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "JobTrendrUserPoolClient": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
    "MongoReadURI": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MyWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "Region": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
  }
}
